#apiVersion: v1
#kind: Service
#metadata:
  #name: split
  #labels:
   # app: split
#spec:
#  ports:
#  - port: 80
    #name: web
  #clusterIP: None
  #selector:
   # app: split

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: split # has to match .spec.template.metadata.labels
  serviceName: "split"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: split # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: split
        image: verchol/split
        env:
        - name: KNAPSACK_API_KEY
          valueFrom:
            secretKeyRef:
              name: knapsack
              key: apikey
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: src
          mountPath: /disk
  volumeClaimTemplates:
  - metadata:
      name: src
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 1Gi